version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  fileuploadapi:
    build: ./FileUploadAPI
    container_name: fileuploadapi_container
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - MongoDB__ConnectionString=mongodb://mongodb:27017
      - MongoDB__DatabaseName=FileUploadDB

volumes:
  mongodb_data:
